server:
  port: 8080

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customers/**
          filters:
          - name: CustomerCircuitBreaker
            args:
              name: customerCircuitBreaker
              fallbackUri: forward:/customer-fallback
        - id: photo-service
          uri: lb://photo-service
          predicates:
            - Path=/photos/**
          filters:
          - name: PhotoCircuitBreaker
            args:
              name: photoCircuitBreaker
              fallbackUri: forward:/photo-fallback

        
