#Application Configuration
server:
  port: 8002
  error:
    include-message: always
spring:
  application:
    name: photo-service
  data:
    mongodb:
      authentication-database: admin
      username: mongoadmin
      password: toor
      database: prueba_bd
      port: 27017
      host: localhost
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/^
Feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"