#Application Configuration
server:
  port: 8002
  error:
    include-message: always
spring:
  application:
    name: photo-service
  data:
    mongodb:
      authentication-database: admin
      username: AdminRoot
      password: M0ng0RD++
      database: prueba_bd
      port: 27017
      host: 142.93.51.124:27017
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"